apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
    env: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
      env: staging
  template:
    metadata:
      labels:
        app: helloworld
        env: staging
    spec:
      containers:
      - name: helloworld
        image: crccheck/hello-world
        ports:
        - containerPort: 80