apiVersion: v1
kind: Pod
metadata:
  name: helloworld-pod
  labels:
    app: helloworld
    env: staging
spec:
  containers:
    - name: helloworld
      image: crccheck/hello-world
      ports:
      - containerPort: 80